id: P000464
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:18.004523
source_metadata:
  id: bdr:W1PD159391
  title: བོད་རིགས་ཀྱི་གཏམ་དཔེ། ༼བོད་རྒྱ་ཤན་སྦྱར།༽
  author: ''
  volumes:
    ee16f43f07864541a6313fbf9d357dff:
      image_group_id: I2PD19660
      title: Volume 1 of bod rigs kyi gtam dpe/
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
